version: '3'
volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:

services:
  foodgram_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data
  backend:
    image: sergeymaximov/foodgram_backend
    env_file: .env
    volumes:
      - foodgram_static:/backend_static
      - foodgram_media:/media_files
    depends_on:
      - foodgram_db
  frontend:
    env_file: .env
    image: sergeymaximov/foodgram_backend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - foodgram_static:/frontend_static
  gateway:
    image: sergeymaximov/foodgram_gateway
    volumes:
      - foodgram_static:/staticfiles/
      - foodgram_media:/media_files_foodgram
    ports:
      - 10000:80