version: '3'
volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:

services:
  foodgram_db:
    build: ./data/
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - foodgram_static:/backend_static
      - foodgram_media:/media_files
    depends_on:
      - foodgram_db
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - foodgram_static:/frontend_static
  gateway:
    build: ./gateway/
    volumes:
      - foodgram_static:/staticfiles/
      - foodgram_media:/media_files_foodgram
    ports:
      - 8000:80
    depends_on:
      - frontend
      - backend