# Generated by Django 4.2.4 on 2023-09-07 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_alter_ingredient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientToRecipe',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodgram.ingredient')),
                ('count', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='foodgram.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='foodgram.recipe')),
            ],
            bases=('foodgram.ingredient',),
        ),
    ]
