# Generated by Django 4.2.4 on 2023-09-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_remove_ingredienttorecipe_recipe_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ForeignKey(default=4001, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipe', to='foodgram.ingredienttorecipe'),
        ),
    ]
