# Generated by Django 4.2.4 on 2023-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_remove_recipe_ingredients_delete_ingredienttorecipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(default=4001, related_name='recipes', to='foodgram.ingredient'),
        ),
    ]
