# Generated by Django 4.2.4 on 2023-09-13 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0009_remove_recipe_ingredients_ingredienttorecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredienttorecipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredienttorecipe',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='foodgram.ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='foodgram.IngredientToRecipe', to='foodgram.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredienttorecipe',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredienttorecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='foodgram.recipe'),
        ),
    ]
