# Generated by Django 4.2.4 on 2023-09-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, default=4001, null=True, related_name='recipes', to='foodgram.ingredient'),
        ),
    ]
