# Generated by Django 4.2.4 on 2023-09-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0016_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='ingredienttorecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='Unique pair constraint.'),
        ),
    ]
